apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: marcusbrandao/api-bootcamp-produto:v2
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "200m"
          # livenessProbe:
          #   httpGet:
          #     path: /helth
          #     port: 8080
          #   initialDelaySeconds:  0
          #   periodSeconds: 5
          #   timeoutSeconds: 1
          #   successThreshold: 1
          #   failureThreshold: 1
          # readinessProbe:
          #   httpGet:
          #     path: /read
          #     port: 8080
          #   initialDelaySeconds:  0
          #   periodSeconds: 5
          #   timeoutSeconds: 1
          #   successThreshold: 1
          #   failureThreshold: 1
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              value:  mongodb://mongouser:mongopwd@mongodb-service:27017/admin
