apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 8080
      #nodePort: 30000
  # k8s local
  #type: NodePort
  #k8s cloud gera ip externo
  type: LoadBalancer